version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=gemups
      - POSTGRES_USER=rendos
      - POSTGRES_PASSWORD=120903Legon
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=gemups
      - DB_USERNAME=rendos 
      - DB_PASSWORD=120903Legon
      - DB_HOST=db
      - DB_PORT=5432
      - CELERY_BROKER_REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
